[archive]
build_output_dir = 'Source\Built'
archive_location = '\\nirvana\Measurements\VeriStandAddons\ballard_arinc_429'

[projects.support]
path = 'Source\Custom Device Support\Ballard ARINC 429 Support.lvproj'

[projects.cd]
path = 'Source\Custom Device\Ballard ARINC 429 Custom Device.lvproj'

[projects.scripting_examples]
path = 'Source\Scripting Examples\Scripting Examples.lvproj'

[[build.steps]]
name = 'Scripting API'
type = 'lvBuildSpec'
project = '{support}'
target = 'My Computer'
build_spec = 'Scripting API'

[[build.steps]]
name = 'Scripting Examples'
type = 'lvBuildSpec'
project = '{scripting_examples}'
target = 'My Computer'
build_spec = 'Examples'

[[build.steps]]
name = 'System Explorer PPL'
type = 'lvBuildSpec'
project = '{support}'
target = 'My Computer'
build_spec = 'System Explorer'

[[build.steps]]
name = 'Engine PPL'
type = 'lvBuildSpec'
project = '{support}'
target = 'My Computer'
build_spec = 'Engine'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Configuration Release'

[[build.steps]]
name = 'Engine Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Engine Release'

[[build.steps]]
name = 'Linux x64 Engine PPL'
type = 'lvBuildSpec'
project = '{support}'
target = 'RT CompactRIO Target - Linux x64'
build_spec = 'Engine'

[[build.steps]]
name = 'Linux x64 Engine Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'RT CompactRIO Target - Linux x64'
build_spec = 'Engine Release'

[[package]]
type = 'nipkg'
control_file = 'control_custom_device'
package_output_dir = 'Source\Built'

[package.payload_map]
'Source\\Built\\Ballard' = 'documents\National Instruments\NI VeriStand {veristand_version}\Custom Devices\Ballard'
'Source\\Built\\Errors' = 'ni-paths-NISHAREDDIR\LabVIEW Run-Time\{veristand_version}\errors\English'

[[package]]
type = 'nipkg'
control_file = 'control_scripting'
package_output_dir = 'Source\Built'

[package.payload_map]
'Source\\Built\\Scripting' = 'ni-paths-LV{veristand_version}DIR\vi.lib\addons\VeriStand Custom Device Scripting APIs\Ballard\ARINC 429'
'Source\\Built\\Scripting Examples' = 'ni-paths-LV{veristand_version}DIR\examples\NI VeriStand Custom Devices\Ballard\ARINC 429'
'Source\\Built\\Errors' = 'ni-paths-LV{veristand_version}DIR\resource\errors\English'
